# Generated by Django 4.1.4 on 2022-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productMainModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('price', models.IntegerField()),
                ('unique_code', models.CharField(max_length=80, unique=True)),
                ('size', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
            ],
        ),
    ]
