# Generated by Django 4.1.4 on 2022-12-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productMainModel1',
            new_name='productMainModel',
        ),
    ]
